services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - C:\Users\Carlos Camargo\Desktop\Universidad\Semestre 9\Arquitectura de Software\Tareas\Varios_logs\logskt:/var/lib/postgresql/data
    networks:
      - currency-network
  currency-converter:
    image: demo:5.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8008:8008"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\Carlos Camargo\Desktop\Universidad\Semestre 9\Arquitectura de Software\Tareas\Varios_logs\logsSpring:/Users/Carlos Camargo/Desktop/Universidad/Semestre 9/Arquitectura de Software/Tareas/logsxd
    networks:
      - currency-network
    depends_on:
      - postgres
  angular:
    image: angular-software:4.0.1
    ports:
      - "4200:80"
    volumes:
      - C:\Users\Carlos Camargo\Desktop\pruebas\currency-front\software\nginx.conf:/etc/nginx/nginx.conf
    networks:
      - currency-network

networks:
  currency-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1
